version: '3.0'

expectations:
  population_size: 1000

actions:

  generate_study_population:
    run: cohortextractor:latest generate_cohort --study-definition study_definition
    outputs:
      highly_sensitive:
        cohort: output/input.csv

  check_hhid:
    needs: [generate_study_population]
    run:  r:latest analysis/check_hhid.R output/input.csv
    outputs:
      moderately_sensitive:
        log: output/check_hhid_log.txt
        fig1: output/household_tpp_coverage.png
        fig2: output/household_size_discrepancies.png
        fig3: output/household_size_discrepancies_constr.png
        fig4: output/household_size_total.png
        fig5: output/household_size_total_constr.png

  repeat_checks_hhid:
    needs: [generate_study_population]
    run:  stata-mp:latest analysis/repeat_checks_hhid.do 
    outputs:
      moderately_sensitive:
        log: output/statalogs/repeat_checks_hhid.log

