version: '3.0'

expectations:
  population_size: 1000

actions:

  generate_study_population:
    run: cohortextractor:latest generate_cohort --study-definition study_definition
    outputs:
      highly_sensitive:
        cohort: output/input.csv

  check_hhid:
    needs: [generate_study_population]
    run:  r:latest analysis/check_hhid.R output/input.csv
    outputs:
      moderately_sensitive:
        log: output/check_hhid_log.txt
        tpp_cov: output/household_tpp_coverage.png
        tpp_size_dist: output/household_size_tpp.png
        tot_size_dist: output/household_size_tot.png


